name: nutricao
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: 10.6.0
  carousel_slider: ^4.2.1
  iconly:
  cupertino_icons: ^1.0.6
  sqflite: ^2.3.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/background.png
    - assets/user.png
    - assets/woman.jpg
    - assets/logo.png